### ISSUE TITLE
Реализовать объектно-реляционное отображение базы данных

### ISSUE THREAD

**Issue by CcyBborg** [CcyBborg/housing-bot#3]
Объектно-реляционное отображение — это технология программирования, которая связывает базы данных с концепциями объектно-ориентированных языков программирования, создавая «виртуальную объектную базу данных».

Необходимо реализовать модуль на сервере для взаимодействия с базой данных.

**Comment by CcyBborg** [comment]
Задача зависит от #1

**Comment by qanelph** [comment]
Добавлено коммитом d20ad47d4580b88fc84d9d4ba37f0be9a148e81f
